// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmmMkYtJF3Y40UmxoFu6f1-Wkad4kaKT8',
    appId: '1:1060583584087:web:ba8592694fc64457b34e12',
    messagingSenderId: '1060583584087',
    projectId: 'fitnessapp-5f810',
    authDomain: 'fitnessapp-5f810.firebaseapp.com',
    storageBucket: 'fitnessapp-5f810.firebasestorage.app',
    measurementId: 'G-2GP6QWJXB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJzqaZy6HLXv8GMdBVA_KiFnVU3wwPzPQ',
    appId: '1:1060583584087:android:1350118594abb8eab34e12',
    messagingSenderId: '1060583584087',
    projectId: 'fitnessapp-5f810',
    storageBucket: 'fitnessapp-5f810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXROk6CVmatf31MSIc3wvjtr9WfXvGNg',
    appId: '1:1060583584087:ios:f1cf0e6119774018b34e12',
    messagingSenderId: '1060583584087',
    projectId: 'fitnessapp-5f810',
    storageBucket: 'fitnessapp-5f810.firebasestorage.app',
    iosBundleId: 'com.example.orderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXROk6CVmatf31MSIc3wvjtr9WfXvGNg',
    appId: '1:1060583584087:ios:f1cf0e6119774018b34e12',
    messagingSenderId: '1060583584087',
    projectId: 'fitnessapp-5f810',
    storageBucket: 'fitnessapp-5f810.firebasestorage.app',
    iosBundleId: 'com.example.orderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmmMkYtJF3Y40UmxoFu6f1-Wkad4kaKT8',
    appId: '1:1060583584087:web:b071ec827421a7eeb34e12',
    messagingSenderId: '1060583584087',
    projectId: 'fitnessapp-5f810',
    authDomain: 'fitnessapp-5f810.firebaseapp.com',
    storageBucket: 'fitnessapp-5f810.firebasestorage.app',
    measurementId: 'G-8WBZ543NRT',
  );
}
