name: Flutter CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build release APK
        run: |
          flutter build apk --release \
            --dart-define=STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --dart-define=STRIPE_TOKEN=${{ secrets.STRIPE_TOKEN }} \
            --dart-define=PAYPAL_SECRET_KEY=${{ secrets.PAYPAL_SECRET_KEY }} \
            --dart-define=PAYMOB_APIKEY=${{ secrets.PAYMOB_APIKEY }}

      #      - name: Build release APK
#        run: flutter build apk --release

      # لو عايز تحتفظ بالـ APK كـ artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
